version: '3'

services:

  # Eclipse Mosquitto MQTT Broker
  mosquitto:
    build:
      context: mqtt-broker
      dockerfile: mqtt-broker/Dockerfile
      args:
        - MOSQUITTO_VERSION=${MOSQUITTO_VERSION:-latest}
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
      - PORT=${MOSQUITTO_PORT}
    image: eclipse-mosquitto:${MOSQUITTO_VERSION:-latest}
    container_name: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./mqtt-broker/data:/mosquitto/data
      - ./mqtt-broker/log:/mosquitto/log
    ports:
      - ${MOSQUITTO_PORT}:${MOSQUITTO_PORT}

  mongo-db:
    image: mongo:4.4
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    env_file:
      - .env
    volumes:
      - ./server/data:/data/db
